title: 'The most information on Garrett Mendez for free!'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.208288585068658
  lightness: 0.7333630819339305
  brandStrength: 0.952202
  brandColors:
    - '#7F4228'
    - '#170B06'
    - '#FFFFFF'
    - '#FAA46D'
    - '#FFCF91'
  rhythmicContrast: 0.1742094475775957
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: The Garrett Mendez
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5547798
layout_spectrum: 1
